"use client";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { ArrowLeft, MessageSquare, Trash2 } from "lucide-react";
import { OperationsAuthWall } from "@/components/operations-auth-wall";
import { useAuth } from "@/lib/auth-context";
import { useLocalization } from "@/lib/localization-context";
import { commentTicket, deleteTicket, getTicket, updateTicket, type TicketStatus } from "@/lib/operations-api";
export default function TicketDetailPage() {
  const { user,isLoading }=useAuth(); const { t }=useLocalization(); const params=useParams<{id:string}>(); const router=useRouter(); const id=String(params.id??"");
  const [data,setData]=useState<Awaited<ReturnType<typeof getTicket>>|null>(null); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  useEffect(()=>{if(isLoading||!user)return;void getTicket(id).then(setData).catch(reason=>setError(reason instanceof Error?reason.message:"Ticket not found"));},[id,isLoading,user]);
  async function add(form:FormData) { const body=String(form.get("comment")??"").trim(); if(!body)return; setBusy(true); try { setData(await commentTicket(id,body)); } catch(reason) { setError(reason instanceof Error?reason.message:"Unable to add comment"); } finally { setBusy(false); } }
  async function status(value:TicketStatus) { setBusy(true); try { setData(await updateTicket(id,value)); } catch(reason) { setError(reason instanceof Error?reason.message:"Unable to update ticket"); } finally { setBusy(false); } }
  async function remove() { if(!data||!window.confirm(t("generated.admin.delete")))return; setBusy(true); setError(null); try { await deleteTicket(id); router.replace("/operations/tickets"); } catch(reason) { setError(reason instanceof Error?reason.message:"Unable to delete ticket"); setBusy(false); } }
  if(isLoading)return <div className="pc-card p-6 text-sm text-pc-text-secondary">{t("generated.operations.ticketLoading")}</div>;
  if(!user)return <OperationsAuthWall/>;
  if(error&&!data)return <div className="pc-card p-6"><Link href="/operations/tickets" className="pc-btn-secondary inline-flex items-center gap-2 text-sm"><ArrowLeft className="h-4 w-4"/>{t("generated.operations.tickets")}</Link><p className="mt-4 text-sm text-pc-text-secondary">{error}</p></div>;
  if(!data)return <div className="pc-card p-6 text-sm text-pc-text-secondary">{t("generated.operations.ticketLoading")}</div>;
  const labels: Record<TicketStatus,string> = { received:t("generated.operations.ticketReceived"), under_review:t("generated.operations.ticketUnderReview"), planned:t("generated.operations.ticketPlanned"), closed:t("generated.operations.ticketClosed") };
  const staff=user?.isAdmin||user?.isProjectDeveloper, own=user?.username===data.ticket.requester, canComment=Boolean(staff||own);
  return <div className="mx-auto max-w-3xl space-y-5"><Link href="/operations/tickets" className="inline-flex items-center gap-2 text-sm text-pc-text-secondary hover:text-pc-accent"><ArrowLeft className="h-4 w-4"/>{t("generated.operations.tickets")}</Link><article className="pc-card p-5"><div className="flex items-start justify-between gap-3"><div><span className="font-mono text-xs text-pc-accent">{data.ticket.code}</span><h1 className="mt-2 text-xl font-bold text-pc-text">{data.ticket.title}</h1></div><span className="rounded-full bg-pc-accent/15 px-2.5 py-1 text-xs font-semibold text-pc-accent">{labels[data.ticket.status]}</span></div><p className="mt-5 whitespace-pre-wrap text-sm leading-6 text-pc-text-secondary">{data.ticket.details}</p></article><section className="space-y-3">{data.comments.map(comment=><article key={comment.id} className="pc-card flex gap-3 p-4"><MessageSquare className="mt-0.5 h-4 w-4 shrink-0 text-pc-accent"/><div className="text-sm text-pc-text-secondary"><span className="mr-1 font-semibold text-pc-text">{comment.author}:</span>{comment.body}</div></article>)}{canComment&&<form action={add} className="pc-card space-y-3 p-4">{staff&&<label className="block text-xs text-pc-text-secondary">{t("generated.operations.projectsStatus")} <select value={data.ticket.status} onChange={e=>void status(e.target.value as TicketStatus)} disabled={busy} className="ml-1 rounded border border-pc-border bg-pc-bg px-2 py-1 text-pc-text">{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>}<textarea required name="comment" rows={4} maxLength={2000} placeholder={t("generated.operations.ticketComment")} className="w-full resize-y rounded-lg border border-pc-border bg-pc-bg px-3 py-2 text-sm text-pc-text"/><button disabled={busy} className="pc-btn-primary text-sm disabled:opacity-60">{t("generated.operations.ticketAddComment")}</button></form>}{staff&&<button type="button" onClick={()=>void remove()} disabled={busy} className="inline-flex items-center gap-2 rounded-lg border border-rose-400/40 px-3 py-2 text-sm font-semibold text-rose-200 hover:bg-rose-400/10 disabled:opacity-60"><Trash2 className="h-4 w-4"/>{t("generated.admin.delete")}</button>}{error&&<p className="text-sm text-rose-200">{error}</p>}</section></div>;
}
